In [1]:
import sys
sys.path.append("..")
import numpy as np

import all_user_votes as auv
from math_calcs import largest_eigen

from ahptree import AhpNode, AhpTree
        

In [2]:
import all_user_nish_excel as nex

In [4]:
all_cmps=nex.from_nish_excel("Nischay/nish_data.xlsx")

['bleeding', 'sore throat', 'gp', 'qol', 'breath']
[[3, 0, 1], [4, 2, 3], [5, 4, 0], [6, 1, 3], [7, 1, 2], [8, 4, 1], [9, 2, 0], [10, 2, 4], [11, 0, 3], [12, 3, 4]]
['L1', 'L2', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'L10', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20', 'B21', 'B22', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'P01', 'P02', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13', 'P14', 'P15', 'M01', 'M02', 'M03', 'M04', 'M05', 'M06', 'M07', 'M08', 'M09', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M19', 'M20', 'M21', 'M22', 'M23', 'M24', 'M25', 'M26', 'M27', 'M28', 'M29', 'M30', 'O1', 'O2', 'O3', 'O4', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'I10', 'I11', 'I12', 'I13', 'K1', 'K2', 'K3', 'K4', 'K5', 'K6', 'K7', 'K8', 'K9', 'K10', 'H1', 'H

In [4]:
ahp = AhpTree(pw=all_cmps)
ahp.add_alt("do")
ahp.add_alt("not")

In [5]:
ahp.root.name

'root'

In [6]:
ahp.root.children[0].name

'bleeding'

In [7]:
ahp.get_node(["bleeding"]).set_alt_scores([0.9, 0.1])
ahp.get_node(["sore throat"]).set_alt_scores([1, .1])
ahp.get_node(["gp"]).set_alt_scores([1., 5])
ahp.get_node(["qol"]).set_alt_scores([2., 4])
ahp.get_node(["breath"]).set_alt_scores([1.,1])

In [8]:
ahp.get_node(["bleeding"]).alt_scores

array([ 1.        ,  0.11111111])

In [9]:
ahp.synthesize(None)

array([ 0.,  0.])

In [10]:
all_cmps.single_stats("L1")

array([ 0.5842173 ,  0.09435708,  0.04526229,  0.25683037,  0.01933295])

In [11]:
all_cmps.group_stats(["L1", "L2"])

array([ 0.19912701,  0.06817219,  0.0978717 ,  0.53851537,  0.09631374])

In [12]:
all_cmps.alt_names

['bleeding', 'sore throat', 'gp', 'qol', 'breath']

In [13]:
all_incons = [all_cmps.inconsistency(uname) for uname in all_cmps.user_names]

In [14]:
negative_indices = [i for i in range(len(all_incons)) if all_incons[i] < 0]

In [15]:
negative_indices

[]

In [16]:
u9 = all_cmps.user_names[9]
u9mat = all_cmps.get_matrix(9)
u9mat

array([[ 1.        ,  1.        ,  0.        ,  0.        ,  3.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  3.        ],
       [ 0.        ,  1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.33333333,  0.33333333,  0.        ,  0.        ,  1.        ]])

In [17]:
u9eigval = largest_eigen(u9mat, value_only=True)
u9eigval

5.0000002569673869

In [18]:
import pandas as pd

In [19]:
raw_data=pd.read_excel('nish_data.xlsx', sheetname='Weight', skiprows=3)

In [21]:
[ahp.synthesize(uname) for uname in all_cmps.user_names]

[array([ 0.167075  ,  0.07915487]),
 array([ 0.12369523,  0.19159372]),
 array([ 0.1614778 ,  0.09750094]),
 array([ 0.12575354,  0.14991004]),
 array([ 0.14711097,  0.11167211]),
 array([ 0.12312189,  0.15255697]),
 array([ 0.18572999,  0.15934246]),
 array([ 0.13782337,  0.14944915]),
 array([ 0.16279755,  0.0820529 ]),
 array([ 0.14000007,  0.11743583]),
 array([ 0.11024032,  0.17476346]),
 array([ 0.14680055,  0.13069521]),
 array([ 0.16901116,  0.09081878]),
 array([ 0.17250127,  0.14893259]),
 array([ 0.18355523,  0.14019496]),
 array([ 0.12579655,  0.17418478]),
 array([ 0.14879581,  0.11797372]),
 array([ 0.16941445,  0.11794566]),
 array([ 0.16753704,  0.07810674]),
 array([ 0.16460756,  0.10709092]),
 array([ 0.12816872,  0.17677778]),
 array([ 0.1571592 ,  0.09628858]),
 array([ 0.14935054,  0.11547682]),
 array([ 0.17072311,  0.16954688]),
 array([ 0.13962355,  0.17575343]),
 array([ 0.12991808,  0.13856824]),
 array([ 0.18048595,  0.15059201]),
 array([ 0.1383726 ,  0.1510