# ISHAP WorkShop code tutorial 
First you would want to start off by importing our source code as seen below.

In [16]:
import commfxs as h
import numpy as np
from plotly.offline import plot
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode()

## Next you would want to calculate the vector for your excel sheet

In [2]:
h.single_stats("Areas.xlsx", "Sarah")

array([ 0.17880869,  0.29666912,  0.17972793,  0.34479426])

In [3]:
h.single_stats('Jobs.xlsx', 'Sarah')

C:\Users\Devin\Anaconda2\lib\site-packages\openpyxl\reader\worksheet.py:322: UserWarning:

Unknown extension is not supported and will be removed



array([ 0.24857039,  0.14602988,  0.20131877,  0.19501841,  0.20906255])

## Next we are going to make the bar chart

In [4]:
drews = h.single_stats("Areas.xlsx", "Drew")

In [5]:
altnames = h.get_altnames("Areas.xlsx")
data = go.Bar(x=["Math", "Animals", "Library", "Kitchen"], y=drews)
layout = go.Layout(title = "Drew's Priorities")
iplot(go.Figure(data = go.Data([data]), layout = layout))

In [6]:
from openpyxl import load_workbook
wb = load_workbook(filename = 'Areas.xlsx')
firstsheet = wb.get_sheet_names()[0]
sheet = wb.get_sheet_by_name(firstsheet)

In [8]:
drews = h.single_stats("Areas.xlsx", "Drew", bars = True)

In [11]:
h.single_stats("Areas.xlsx", "Sarah")

array([ 0.17880869,  0.29666912,  0.17972793,  0.34479426])

In [12]:
h.single_stats("Areas.xlsx", "Sarah", better = 1./3, muchbetter = 1./9)

array([ 0.18679959,  0.24011725,  0.39996441,  0.17311876])

In [17]:
h.Largest_eigen(np.array([[1., 3],[1./3, 1]]))

array([ 0.75,  0.25])

In [18]:
h.Largest_eigen(np.array([[1., 3, 6],[1./3, 1, 2], [1./6, 1./2, 1]]))

array([ 0.66666667,  0.22222222,  0.11111111])