# Tutorial on looping and matrices
This tutorial guides you through the basics of creating matrices and using loops in python to do basic operations on matrices.

## 1. Import the needed libraries

In [1]:
import numpy as np

## 2. Start with vectors
Vectors are just one dimensional matrices.  In programming we call them arrays.  Here are some examples

In [4]:
vect1 = np.array([1, 3, 5])
vect2 = np.array([-1, 0, 1])
vect3 = np.array([10, 100, 1/6., 17.6])
print(vect1)
print(vect2)
print(vect3)

[1 3 5]
[-1  0  1]
[  10.          100.            0.16666667   17.6       ]


As you can see, a __vector__ is simply a list of numbers.

### 2.1 Creating a vector programmatically
Let's create the array [1, 4, 9, 25, 36, 49, 64, 81, 100, 121] via code.  This is the list of the squares of numbers from 1 to 11.

In [10]:
#Create an empty list
squares = list()
#Now append elements to it
for i in range(1, 12):
    squares.append(i*i)
squares = np.array(squares)
squares

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

__NOTE__:  We created a _list_ first, and then created the numpy vector.  The reason for this is the numpy arrays are not designed to grow easily, but lists are.  Thus we created a list first, then created the numpy array.

### 2.2 Exercises
1. Create a vector of the cubes of 1,2,3,...,100
2. Create a vector of all 0's.
3. Create a vector of all 1's.