# Tutorial on looping and matrices
This tutorial guides you through the basics of creating matrices and using loops in python to do basic operations on matrices.

## 1. Import the needed libraries

In [1]:
import numpy as np

## 2. Start with vectors
Vectors are just one dimensional matrices.  In programming we call them arrays.  Here are some examples

In [4]:
vect1 = np.array([1, 3, 5])
vect2 = np.array([-1, 0, 1])
vect3 = np.array([10, 100, 1/6., 17.6])
print(vect1)
print(vect2)
print(vect3)

[1 3 5]
[-1  0  1]
[  10.          100.            0.16666667   17.6       ]


As you can see, a __vector__ is simply a list of numbers.

### 2.1 Creating a vector programmatically
Let's create the array [1, 4, 9, 25, 36, 49, 64, 81, 100, 121] via code.  This is the list of the squares of numbers from 1 to 11.

In [10]:
#Create an empty list
squares = list()
#Now append elements to it
for i in range(1, 12):
    squares.append(i*i)
squares = np.array(squares)
squares

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

__NOTE__:  We created a _list_ first, and then created the numpy vector.  The reason for this is the numpy arrays are not designed to grow easily, but lists are.  Thus we created a list first, then created the numpy array.

### 2.2 Exercises
1. Create a vector of the cubes of 1,2,3,...,100
2. Create a vector of all 0's.
3. Create a vector of all 1's.

### 2.3 Some vector arithmetic
The numpy library already has code to do vector arithmetic in it, here are some examples, using previously defined vectors.

In [12]:
print(vect1+vect2)
print(vect1-vect2)

[0 3 6]
[2 3 4]


However, we should see how to define these ourselves.  It will help us better understand the process of vector arithmetic.

In [16]:
def vec_plus(v1, v2):
    """
    Adds v1 to v2 and returns the result.  If the vectors do not have the same length, it throws and error
    """
    if len(v1) != len(v2):
        raise IndexError("v1 and v2 must have the same size")
    #Let's first get the length of these vectors, if we've made it here, they have the same length
    size = len(v1)
    #Create a new vector of this size that will be the result we return.  We start with all values zero
    #knowing that we will fill it in eventually
    rval = np.zeros(size)
    #Now we need to loop over the size of these vectors, adding each individual entry
    for position in range(0, size):
        rval[position] = v1[position]+v2[position]
    #That is it, we are done
    return(rval)

**Note:** vec_plus works on any types that have a length and size, let's try it on a few examples

In [19]:
print(vec_plus(vect1, vect2))
print(vec_plus([1,5], [2, 4]))

[ 0.  3.  6.]
[ 3.  9.]


We added two lists in the second example, and got a result (the second example did not have np.array's as the argument)

### 2.4 Exercises
1. Create a vec_minus(v1,v2) function that subtracts one vector from another
2. Write some examples using vec_minus.
3. Create a vec_multiply(v1,v2) function that multiplies the entries in one vector by the entries in another.
4. Write some examples using vec_multiply
5. Create a vec_scalar(numb, v1) the first argument is a number, and the second argument is a vector.  This function should multiply each element of v1 by the number *numb*.  I.e. vec_scalar(3, [1, 4, -2]) should return [3, 12, -8].